name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Cache pnpm dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: |
          npm config set registry https://registry.npmmirror.com
          pnpm install

      - name: Build
        run: |
          # ✅ 修复1：正确的编译命令（对应 --mode prod，读取 .env.prod）
          # ✅ 修复2：覆盖 .env.prod 中的 localhost 为真实服务器地址
          # ✅ 修复3：覆盖输出目录为 dist，方便后续步骤统一处理
          VITE_BASE_URL=http://114.55.24.12:48080 \
          VITE_MALL_H5_DOMAIN=http://114.55.24.12:48080 \
          VITE_OUT_DIR=dist \
          pnpm build:prod

      - name: Verify dist
        run: |
          if [ -d "dist" ]; then
            echo "✅ dist 目录存在"
            ls -lh dist/
          else
            echo "❌ dist 目录未找到，编译失败"
            exit 1
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          commit_message: "Deploy: ${{ github.sha }}"
